apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: default
  volumeMode: Filesystem